ALTER TABLE persons RENAME COLUMN address TO full_address_legacy;

ALTER TABLE persons
ADD COLUMN IF NOT EXISTS identification_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS identification_value VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255),
ADD COLUMN IF NOT EXISTS postcode VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS state VARCHAR(255),
ADD COLUMN IF NOT EXISTS country VARCHAR(255);
